name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: inventory-optimization-app
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Run from source
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        source: .
        flags: |
          --allow-unauthenticated
          --memory=512Mi
          --cpu=1
          --timeout=60
          --concurrency=80
          --port=8501
          --min-instances=0
          --max-instances=100
